# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcualator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_cal = QtWidgets.QPushButton(self.centralwidget)
        self.Button_cal.setGeometry(QtCore.QRect(600, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_cal.setFont(font)
        self.Button_cal.setIconSize(QtCore.QSize(60, 60))
        self.Button_cal.setObjectName("Button_cal")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 100, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.Button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.Button_plus.setGeometry(QtCore.QRect(250, 0, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Button_plus.setFont(font)
        self.Button_plus.setObjectName("Button_plus")
        self.Button_zarb = QtWidgets.QPushButton(self.centralwidget)
        self.Button_zarb.setGeometry(QtCore.QRect(250, 140, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Button_zarb.setFont(font)
        self.Button_zarb.setObjectName("Button_zarb")
        self.Button_manfi = QtWidgets.QPushButton(self.centralwidget)
        self.Button_manfi.setGeometry(QtCore.QRect(250, 70, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(90)
        self.Button_manfi.setFont(font)
        self.Button_manfi.setObjectName("Button_manfi")
        self.Button_tagsim = QtWidgets.QPushButton(self.centralwidget)
        self.Button_tagsim.setGeometry(QtCore.QRect(250, 210, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.Button_tagsim.setFont(font)
        self.Button_tagsim.setObjectName("Button_tagsim")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 100, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 110, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lableScreen = QtWidgets.QLabel(self.centralwidget)
        self.lableScreen.setGeometry(QtCore.QRect(480, 5, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lableScreen.setFont(font)
        self.lableScreen.setStyleSheet("")
        self.lableScreen.setObjectName("lableScreen")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Button_cal.clicked.connect(self.hesab)
        self.Button_plus.clicked.connect(self.jam)
        self.Button_manfi.clicked.connect(self.taf)
        self.Button_zarb.clicked.connect(self.zarb)
        self.Button_tagsim.clicked.connect(self.tag)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_cal.setText(_translate("MainWindow", "حساب کن"))
        self.lineEdit.setText(_translate("MainWindow", ""))
        self.Button_plus.setText(_translate("MainWindow", "+"))
        self.Button_zarb.setText(_translate("MainWindow", "*"))
        self.Button_manfi.setText(_translate("MainWindow", "-"))
        self.Button_tagsim.setText(_translate("MainWindow", "/"))
        self.lineEdit_2.setText(_translate("MainWindow", ""))
        self.label.setText(_translate("MainWindow", ">>>     "))
        self.lableScreen.setText(_translate("MainWindow", "Screen:   "))

    def jam(self):
        self.lableScreen.setText(self.lineEdit.text() + " + " + self.lineEdit_2.text())
    def taf(self):
        self.lableScreen.setText(self.lineEdit.text() + " - " + self.lineEdit_2.text())
    def zarb(self):
        self.lableScreen.setText(self.lineEdit.text() + " * " + self.lineEdit_2.text())
    def tag(self):
        self.lableScreen.setText(self.lineEdit.text() + " / " + self.lineEdit_2.text())

    def hesab(self):
        neveshte = self.lableScreen.text()
        try:
            javab = eval(neveshte)
            self.lableScreen.setText(str(f"{neveshte} = {javab}"))
            self.label.setText(str(javab))
 
        except Exception as error:
            self.lableScreen.setText(" لطفا با توجه به Readme دوباره امتحان کنید.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
